### ISSUE TITLE
No TCommandSend ipschan parameter in connect_sensors

### ISSUE THREAD

**Issue by davidbenncsiro** [StefanSimis/PyTrios#5]
With a G1 device connected via an IPS box on channel 4, the sensor does not respond. 

Invocations of the `TCommandSend` function in `TClasses.py` pass an `ipschan` parameter in [all but one case](https://github.com/StefanSimis/PyTrios/blob/master/pytrios/radman.py#L382).

For example, code in `handlePacket` ([`pytrios1.py`](https://github.com/StefanSimis/PyTrios/blob/master/pytrios/pytriosg1.py#L37)) handles N possible channels for the specified serial port.

In the `connect_sensors` function ([`radman.py`](https://github.com/StefanSimis/PyTrios/blob/master/pytrios/radman.py#L382)), no `ipschan` parameter is passed, so the default value of `00` is used.

After modifying the code locally to specify the channel, the G1 responds as expected:
~~~
ps.TCommandSend(com, commandset=None, ipschan='08', command='query')
~~~

`connect_sensors` currently appears to assume that there are N>=1 serial connected devices as opposed to a single serial port connected to an IPS box with N channels. Should the code there do something more like this?
~~~
for c in ['02', '04', '06', '08']:
  ps.TCommandSend(com, commandset=None, ipschan=c, command='query')
~~~

Thanks for your work!

**Comment by StefanSimis** [comment]
Hi David

Thanks for spotting this and I can see how this would cause issues. I don't have an IPS box at the moment to test, so will keep this open for others to follow in the first instance. I think there might be a few more tweaks needed to use these functions either both with and without the additional layer of addressing from the IPS box - the port object gets passed around a lot and the G1 library is a bit of a beast, very much because of these nested connections. Note that the G2 library does not even support the use of the IPS box.. 

Stefan

**Comment by davidbenncsiro** [comment]
Hi Stefan

Further to the above, suppose I wanted to make a change to the code block in `connect_sensors` function ([`radman.py`](https://github.com/StefanSimis/PyTrios/blob/master/pytrios/radman.py#L377)):
~~~
      for com in self.coms:
          # set verbosity for com channel (com messages / errors)
          # 0/1/2 = none, errors, all
          com.verbosity = 1
          # query connected instruments
          ps.TCommandSend(com, commandset=None, command='query')
~~~
such that it included the `ipschan`, as we have in `handlePacket` ([`pytrios1.py`](https://github.com/StefanSimis/PyTrios/blob/master/pytrios/pytriosg1.py#L37)), in this context would it make sense to do this:
~~~
      for com in self.coms:
          for chan in ['02', '04', '06', '08']:
              # set verbosity for com channel (com messages / errors)
              # 0/1/2 = none, errors, all
              com.verbosity = 1
              # query connected instruments
              ps.TCommandSend(com, commandset=None, ipschan=chan, command='query')
~~~
or would it also be necessary to add a SAM query?
~~~
TCommandSend(com, commandset='SAM', ipschan=chan, command='query_sam')
~~~
giving this:
~~~
      for com in self.coms:
          for chan in ['02', '04', '06', '08']:
              # set verbosity for com channel (com messages / errors)
              # 0/1/2 = none, errors, all
              com.verbosity = 1
              # query connected instruments
              ps.TCommandSend(com, commandset=None, ipschan=chan, command='query')
              ps.TCommandSend(com, commandset='SAM', ipschan=c, command='query_sam')
~~~
An alternative is that I *could* pass `ipchan` down through to `connect_sensors` via the `TriosManager` constructor via `run_sample` in `sample_trios.py` with an IPS channel command-line parameter. Given that `connect_sensors` calls `_identify_sensors` which looks for SAM instruments, I don't know whether that would be sufficient however. Then again, since hardcoding `ipschan='08'` (as per the initial description) worked, perhaps the `query_sam` is not required, at least in our local scenario.

Also, how do we want to manage such changes? Pull-requests via branches, or forking, or would you prefer to make such a change?

Thanks.

**Comment by StefanSimis** [comment]
Hi David

I think no additional query is necessary when you direct each query to the right subchannel. It is not necessary to set the verbosity in every loop so you could use 
```
      for com in self.coms:
          com.verbosity = 1
          for chan in ['02', '04', '06', '08']:
              # query connected instruments
              ps.TCommandSend(com, commandset=None, ipschan=chan, command='query')
```
Very much appreciated that you are testing this - cheers

**Comment by StefanSimis** [comment]
Once you are satisfied with testing, I'd be happy to integrate the changes into the main branch via pull request.

**Comment by davidbenncsiro** [comment]
Thanks Stefan! I suspect I will need additional (write) permissions on this repo to be able to create a branch and pull request.

**Comment by davidbenncsiro** [comment]
@StefanSimis, I've committed the fix discussed above on a branch. Gemma and I will test this before creating a pull request. Thanks.

**Comment by davidbenncsiro** [comment]
@StefanSimis, Gemma and I have tested the IPS box and one-sensor scenario against the code changes for the `ipschan` parameter in `connect_sensors` I committed on July 31st.

It worked as expected! In addition, Gemma and I tested the code changes with two sensors connected and that also worked as expected.

So, I’ll create a pull request for your review and merging if you’re happy.

During our testing we also noticed that specifying an integration time of zero via `sample_pytrios.py`’s `-i` argument did not allow that to work as an auto integration time specifier and the script exited with an unknown sensor type error. This is because the `type` and zero `inttime` arguments were considered together, leading to the final else case being reached.

I’ve tested and committed a fix for this as well, on the same branch. If you would prefer me to create a separate GitHub issue and branch for this, I’m happy to do so.

**Comment by davidbenncsiro** [comment]
As a further refinement to the integration time argument code, we may be able to do something like this instead:
~~~
elif args.type == 1:
        permitted_inttimes = [2**n for n in range(3, 14)]
        if args.inttime != 0 and args.inttime not in permitted_inttimes:
                log.info("Integration time for G1 sensors must be 0 (auto) or one of {} ms",
                             ", ".join(permitted_inttimes))
                sys.exit()
    elif args.type == 2:
        permitted_inttimes = [2**n for n in range(2, 14)]
        if args.inttime != 0 and args.inttime not in permitted_inttimes:
                log.info("Integration time for G2 sensors must be 0 (auto) or one of {} ms",
                             ", ".join(permitted_inttimes))
...
~~~
See #10
