### ISSUE TITLE
Serial port names assume *nix in TSerial

### ISSUE THREAD

**Issue by davidbenncsiro** [StefanSimis/PyTrios#6]
The [`TSerial`](https://github.com/StefanSimis/PyTrios/blob/master/pytrios/TClasses.py#L30) class assumes *nix of some kind (Linux, Unix, MacOSX) re: the naming of serial ports.

On Windows the serial port name will be `COMn`, e.g. `COM4`.

Removing this line locally:
~~~
port = "/dev/ttyUSB"+port.strip('/dev/ttyUSB')
~~~
works for Windows but may not be the solution required for other operating systems.

Thanks.

**Comment by StefanSimis** [comment]
Hi David, you are correct - that does seem a bit too prescriptive. Much better to provide the full address of the port i.e. '/dev/ttyUSBx' on *nix and 'COMx' on windows.
